/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as YoutubeIndexImport } from './routes/youtube/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const YoutubeIndexRoute = YoutubeIndexImport.update({
  id: '/youtube/',
  path: '/youtube/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/youtube/': {
      id: '/youtube/'
      path: '/youtube'
      fullPath: '/youtube'
      preLoaderRoute: typeof YoutubeIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/youtube': typeof YoutubeIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/youtube': typeof YoutubeIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/youtube/': typeof YoutubeIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/youtube'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/youtube'
  id: '__root__' | '/' | '/youtube/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  YoutubeIndexRoute: typeof YoutubeIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  YoutubeIndexRoute: YoutubeIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/youtube/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/youtube/": {
      "filePath": "youtube/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
